# -*- coding: utf-8 -*-
"""Rectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wfc4tZlCVoTL8Q9dAGperwuYaC4kRlVj
"""

import numpy as np

n = 2
b = []

'''
for i in range(n):
  a = []
  for i in range(4):
    c, d = input().split()
    a.append((int(c), int(d)))
  b.append(np.array(a))

a = np.array(b)
print(a)

'''

def printRect(rec):
  for i in range(4):
    x, y = [], []
    for j in range(2):
      if(i+j<4):
        x.append(rec[i+j][0])
        y.append(rec[i+j][1])
      else:
        x.append(rec[0][0])
        y.append(rec[0][1])
    plt.plot(x, y)

def dist(rec1, rec2):
  direc = [[0, 0] for i in range(4)]
  for i in range(4):
    for j in range(2):
      direc[i][j] = 1 if rec2[i][j] - rec1[i][j] >= 0 else 0
  return direc

b.append([[ 0,  0],  [ 1,  0],  [ 1,  1],  [ 0,  1]])
b.append([[ 3, -1],  [ 4, -1],  [ 4,  0],  [ 3,  0]])

# %matplotlib inline
import matplotlib.pyplot as plt

printRect(b[0])
printRect(b[1])

print(dist(b[0], b[1]))
plt.axis('scaled')
plt.show()
